### ISSUE TITLE
[BUG]: Game crashes due to missing registry object on servers

### ISSUE THREAD

**Issue by morganmcg0404** [DonovanDMC/ProjectExpansion#100]
**Description**
Ran these mods in singleplayer no issue, tried running it on a server and it crashes the second you hover any item. The crash report is reporting that its caused by "Registry Object not present: projectexpansion:alchemical_collection".

**Minecraft Version**
1.19.2

**ProjectExpansion Version**
1.0.8

**Forge Version**
43.2.11

**Reproduction Steps**
Load the mod on a server and hover any item in your inventory or JEI and game crashes

**Crash Report/Logs**
[crash-2023-06-20_01.15.24-client.txt](https://github.com/DonovanDMC/ProjectExpansion/files/11794082/crash-2023-06-20_01.15.24-client.txt)

**Other Mods**
ATM8 version 8-1.0.19b
Equivalent Additions 19.1.2
Expanded Equivalence 19.1.2
ProjectE 1.0.1B

**Comment by DonovanDMC** [comment]
Can't reproduce with just JEI, I'm not taking on an issue with almost 400 mods
