### ISSUE TITLE
Power flowers are not learnable to transmutation table

### ISSUE THREAD

**Issue by Josh71293** [DonovanDMC/ProjectExpansion#101]
Project expansion: 1.0.40
Forge:36.2.34
Minecraft:1.16.5
Issue:
I created a new world and gave myself the transmutation table to test it out. After learning the tome of knowledge, I noticed the power flowers and final star had no emc values and, were, thus, unlearnable.
Expected: power flowers and final star have corresponding emc values.
Outcome: none of the power flowers have emc values and neither does the final star.

**Comment by DonovanDMC** [comment]
I can't reproduce this
I'll need more information

**Comment by Josh71293** [comment]
I was able to fix the issue by enabling a pregenerate file for project e and copying over missing values from a separate pregenerate file which had the proper values.
