### ISSUE TITLE
"Non [a-z0-9/._-] character in path of location: projectexpansion:pınk_matter" on starting server

### ISSUE THREAD

**Issue by hssndrms** [DonovanDMC/ProjectExpansion#102]
hi, while loading the server it gives an error about the pink_matter object. the error log is attached. While searching for the cause of the error, I found that other mods had a similar problem.
In issue #94 you replied "That's a perfectly valid path, look into the other mods you're using.". 

Could the problem be caused by using toLowerCase() without specifying the locale?
as you know this function works by locale. If you don't point out the desired locale, it uses systems locale. In my case; "PINK_MATTER" to "pınk_matter" which has a non English character "ı" 
because the language of the computer I use is not English.

I think changing "this.name = name().toLowerCase();" to "this.name = name().toLowerCase(Locale.US);" on line 95 in "[‎src/main/java/cool/furry/mc/forge/projectexpansion/util/Matter.java](https://github.com/DonovanDMC/ProjectExpansion/blob/5e109a8879b69c6bc718062f5d5e3c925b424735/src/main/java/cool/furry/mc/forge/projectexpansion/util/Matter.java#L95)" may fix the problem

Minecraft Version
1.16.5

ProjectExpansion Version
1.0.40

Forge Version
36.2.34

[crash-2023-08-03_02.04.39-fml.txt](https://github.com/DonovanDMC/ProjectExpansion/files/12245425/crash-2023-08-03_02.04.39-fml.txt)

**Comment by DonovanDMC** [comment]
Fixed in [1.0.10](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.19.2-1.0.10) for 1.19.2
This fix *may* come to other versions, depending on how easy the port is for everything else, and how much overall freetime I have

**Comment by DonovanDMC** [comment]
1.18: [1.0.21](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.18.2-1.0.21)
1.16: [1.0.41](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.41)
