### ISSUE TITLE
server

### ISSUE THREAD

**Issue by Nessuno6** [DonovanDMC/ProjectExpansion#105]
If I'm not online on the server my links don't work, is there a way to make them work?

**Comment by DonovanDMC** [comment]
No, this is a very intentional restriction

**Comment by Nessuno6** [comment]
I'm not trying to be controversial and I apologize if the question is biased but I realy would like to know why

**Comment by DonovanDMC** [comment]
Editing the emc of offline players is next to impossible in a safe manner due to capabilities not working on offline players

**Comment by Nessuno6** [comment]
ohhh, it makes a lot sense but I didn't think that because we were playing with the Team ProjectE mod that shares the EMC between me and my friend
