### ISSUE TITLE
Power Flower block Project Expansion

### ISSUE THREAD

**Issue by gdawson521** [DonovanDMC/ProjectExpansion#107]
Hi, i built the power flower block but it isnt generating EMC it is on top of my energy condenser, am i doing this wrong or is there anywhere i can get some direction, i would advise you make a manual ingame because there is no wiki help

**Comment by DonovanDMC** [comment]
There [is a wiki](https://github.com/DonovanDMC/ProjectExpansion/wiki/Power-Flowers), they generate emc passively which goes directly into your emc
