### ISSUE TITLE
Crashing when using the alchemical book

### ISSUE THREAD

**Issue by Frodonand** [DonovanDMC/ProjectExpansion#109]
Hey,

I'm playing the modpack "Crazy-Craft-Updated" on version 0.10.0B which includes the Project Expansion mod.

I just got to the point where I could craft a master alchemical book but using it will result in the game crashing instantly.

Here's the log in short, I'm attaching a full version:

`The game crashed whilst unexpected error
Error: java.lang.IllegalAccessError: tried to access method net.minecraft.entity.LivingEntity.func_226268_ag_()Lnet/minecraft/util/math/BlockPos; from class cool.furry.mc.forge.projectexpansion.gui.GUIAlchemicalBook`

[crash-2023-11-13_12.38.46-client.txt](https://github.com/DonovanDMC/ProjectExpansion/files/13334371/crash-2023-11-13_12.38.46-client.txt)

Edit: Minecraft Version is 1.16.5 and it appears to be happening with any alchemical book.

**Comment by DonovanDMC** [comment]
I can't reproduce this outside of that modpack, which has well over 300 mods
I'm not taking this on if it only happens within an environment very likely to have incompatibilities
