### ISSUE TITLE
[BUG]: EMC link tooltips have incorrect values.

### ISSUE THREAD

**Issue by loldev69** [DonovanDMC/ProjectExpansion#113]
**Description**
EMC link tooltips show fluid limit in place of item limit and EMC limit in place of fluid limit.
This is because of a small error [in the appendHoverText method](https://github.com/DonovanDMC/ProjectExpansion/blob/1.18/src/main/java/cool/furry/mc/forge/projectexpansion/block/BlockEMCLink.java#L50) of the BlockEMCLink class, which passes the wrong values when building the tooltip as of [this commit](https://github.com/DonovanDMC/ProjectExpansion/commit/26ac36e942f3e0b32aa4eca1a6c4372d4ebdf2d5).
Actual block functionality is not affected, so this is pretty low priority.
I've tested on 1.18.2, but looking at the code the issue is also present in the other versions.

**Minecraft Version** 1.18.2
**Forge Version** 40.2.14
**ProjectE Version** 1.01
**ProjectExpansion Version** 1.18.2-1.0.21

**Comment by DonovanDMC** [comment]
This should be fixed in 1.1.0 of 1.18+
* [1.18.2](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.18.2-1.1.0)
* [1.19.2](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.19.2-1.1.0)
* [1.20.1](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.20.1-1.1.0)
