### ISSUE TITLE
'projectexpansion:transmutation_interface' has som bugs

### ISSUE THREAD

**Issue by gjmhmm8** [DonovanDMC/ProjectExpansion#118]
**Description**

when a stack nbt item in it will be disappear
**Minecraft Version**

1.20.1 ATM9
**ProjectExpansion Version**

**Forge Version**

**Reproduction Steps**

**Crash Report/Logs**

**Other Mods**

**Comment by DonovanDMC** [comment]
You didn't bother actually filling out the report, so I'm not going to bother putting any time into this.
