### ISSUE TITLE
[BUG]: Transmutation Interface causes lag when read by a Refined Storage External Storage Device in ATM9 Modpack.

### ISSUE THREAD

**Issue by Furious1964** [DonovanDMC/ProjectExpansion#119]
**Description**
Massive lag generated by reading the Transmutation Interface with an External Storage Bus from Refined Storage. Also, EMC being generated by the Power Flowers fluctuates constantly instead of being steady. Can you please look into this. When I remove the Transmutation Interface, all goes back to normal.

**Minecraft Version**
1.20.1

**ProjectExpansion Version**
1.0.0

**Forge Version**
47.2.19

**Reproduction Steps**
 1. Place down a Transmutation Interface
 2. Connect a Refined Storage Network to device with an External Storage Bus.
 3. See generated EMC fluctuate and try to eat or drink anything....action takes longer then expected, indicating Lag.

**Crash Report/Logs**
N/A

**Other Mods**
Running the ATM9 Modpack, added Porject E to the pack.

**Comment by DonovanDMC** [comment]
The lag is coming from RS being made badly, it performs terribly in general. The block performs just fine eith AE2.

EMC generated from power flowers will always show as unsteady, that's a consequence of the way they update.

**Comment by Furious1964** [comment]
Will try changing RS to AE2 and see what happens. Thanks for your help.
