### ISSUE TITLE
[BUG]: projectexpansion:transmutation_interface

### ISSUE THREAD

**Issue by gjmhmm8** [DonovanDMC/ProjectExpansion#120]
**Description**
items with emc and nbt put in projectexpansion:transmutation_interface will last 1

**Minecraft Version**
1.20.1

**ProjectExpansion Version**
1.0.0

**Forge Version**
47.2.19

**Reproduction Steps**
1 put projectexpansion:transmutation_interface and ae2:storage_bus
2 put items in ae like this Item.of('minecraft:iron_ingot', 64, "{display:{Name:'{\"text\":\"ingot\"}'}}") 
3 it will be last 1

**Crash Report/Logs**

[crash-2024-02-01_07.01.03-client.txt](https://github.com/DonovanDMC/ProjectExpansion/files/14118189/crash-2024-02-01_07.01.03-client.txt)
[latest.log](https://github.com/DonovanDMC/ProjectExpansion/files/14118191/latest.log)

**Other Mods**

ATM 9 with projecte and this

**Comment by gjmhmm8** [comment]
1 item and 2 items can't be storged with no disk

**Comment by gjmhmm8** [comment]
Item.of('ae2:item_storage_cell_64k', '{amts:[L;1L],ic:1L,keys:[{"#c":"ae2:i",id:"minecraft:iron_ingot",tag:{display:{Name:\'{"text":"ingot"}\'}}}]}')
<img width="283" alt="Snipaste_2024-02-01_07-15-47" src="https://github.com/DonovanDMC/ProjectExpansion/assets/73775469/cd4d2e0d-a70f-48b6-9ba0-bca972f3e806">

**Comment by GigaOtomia** [comment]
You might need to be a bit more clear about what you mean by "last 1".

**Comment by gjmhmm8** [comment]
last 1 item in ae

**Comment by gjmhmm8** [comment]
you can try yourself

**Comment by DonovanDMC** [comment]
I have no idea what you're getting at here, but I can't find any bug within basic usage of a transmutation interface

**Comment by gjmhmm8** [comment]
/give @p minecraft:iron_ingot{display:{Name:'{"text":"ingot"}'}} 64

**Comment by GigaOtomia** [comment]
I think the bug he's getting at is that the interface (whether on AE's side or Expansion's) doesn't recognize an iron ingot with a different NBT tag as a plain iron ingot, which... isn't a bug, to my knowledge? The game uses NBT tags to differentiate other items like potions or enchantments, so it makes sense that if you add an NBT tag to an item, it would stop registering that item as the same as one without that tag

**Comment by DonovanDMC** [comment]
If that is the problem, then yes, that's very much intentional
https://github.com/DonovanDMC/ProjectExpansion/wiki/Transmutation-Interface#nbt-filtering

**Comment by gjmhmm8** [comment]
it will be disappear，the num change from 64 to2

**Comment by gjmhmm8** [comment]
https://github.com/DonovanDMC/ProjectExpansion/assets/73775469/48f7e069-ee3c-47e9-ae3a-2ddbb2b69d6d
