### ISSUE TITLE
[BUG]: Alchemical Book location list overflows off the screen

### ISSUE THREAD

**Issue by ThePython10110** [DonovanDMC/ProjectExpansion#125]
**Description**
The Alchemical Book location list overflows off the right side of the screen if you have enough locations.
There should probably either be multiple pages of locations or a scrollbar.

**Minecraft Version**

**ProjectExpansion Version**

**Forge Version**

**Reproduction Steps**
1. Get any Alchemical Book
2. Set lots of locations (on my screen, it takes over 30 to make it overflow)

**Crash Report/Logs**

[crash-2024-03-01_14.05.24-client.txt](https://github.com/DonovanDMC/ProjectExpansion/files/14466483/crash-2024-03-01_14.05.24-client.txt)

**Comment by DonovanDMC** [comment]
In addition to adding pagination I'm making it scale with the gui, on my computer at full screen:
gui scale = WxH, total
1 scale = 14x33, 462
2 scale = 7x16, 112
3 scale = 4x11, 44
4 scale = 3x8, 24

**Comment by DonovanDMC** [comment]
Fixed in [1.1.2](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.20.1-1.1.2)
