### ISSUE TITLE
Final Star duping

### ISSUE THREAD

**Issue by XH14MZAH3** [DonovanDMC/ProjectExpansion#126]
**Description**
Can't dupe with Final Star (cant right click it while its on the dm pedestal).

**Minecraft Version**
1.19.2

**ProjectExpansion Version**
1.19.2

**Forge Version**
1.19.2

**Reproduction Steps**
Place DM Pedestal
Put Final Star on
Try to Right-Click

**Crash Report/Logs**
none

**Other Mods**
Flux Networks, JourneyMap, JEI, Mekanism, Mekanism Generators, AE2, Cyclic, EnderStorage, ProjectE, ProjectExpansion, OreExcavation, IndustrialForegoing, The One Probe, AppleSkin.

**Comment by DonovanDMC** [comment]
That is not a feature of this mod

**Comment by XH14MZAH3** [comment]
So what is the point of the Final star -_-

**Comment by DonovanDMC** [comment]
![image](https://github.com/DonovanDMC/ProjectExpansion/assets/17226394/0ac2f490-5199-4cfc-8a4d-0fe82a462513)

**Comment by XH14MZAH3** [comment]
So it is one of the most time-consuming things to make and it only has ONE
use. Absolute stupidity.

**Comment by DonovanDMC** [comment]
Don't craft it then? I don't know what to tell you

**Comment by XH14MZAH3** [comment]
Can you refer me to the mod that can actually do this?

**Comment by DonovanDMC** [comment]
no
