### ISSUE TITLE
[BUG]: Missing items

### ISSUE THREAD

**Issue by AK16bit** [DonovanDMC/ProjectExpansion#128]
**Description**
magnum, colossal, and gargantuan klien stars don't exist in the creativebar and JEI .

**Minecraft Version**
1.20.1

**ProjectExpansion Version**
1.1.0

**Forge Version**
47.2.30

**Reproduction Steps**
1.Open your Inventory
2.Try to find it

**Comment by DonovanDMC** [comment]
Known issue, already fixed and awaiting release

**Comment by DonovanDMC** [comment]
Fixed in [1.1.1](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.20.1-1.1.1)
