### ISSUE TITLE
[BUG]: EMC Not showing in top left corner

### ISSUE THREAD

**Issue by readytodream** [DonovanDMC/ProjectExpansion#130]
**Description**
 I have EMC set to showing in the configs but it's not on the screen.

**Minecraft Version**
1.19.2

**ProjectExpansion Version**
1.19.2-1.1.0

**Forge Version**
43.3.13

**Reproduction Steps**
1. Set config to on
2. Have EMC displayed on screen

**Crash Report/Logs**

**Other Mods**
I've added it to the TechRevolution pack

**Comment by DonovanDMC** [comment]
There's nothing for me to debug here, you need to look into this yourself
