### ISSUE TITLE
[BUG]: Missing advancement text for yellow fuel item and block

### ISSUE THREAD

**Issue by nayfaan** [DonovanDMC/ProjectExpansion#131]
**Description**
The advancement text for yellow fuel item/block are missing. See image below.
<img width="1680" alt="スクリーンショット 2024-06-03 13 35 23" src="https://github.com/DonovanDMC/ProjectExpansion/assets/10527873/79772f9f-3bcc-4e57-b604-5708e0336a55">
<img width="1680" alt="スクリーンショット 2024-06-03 13 35 24" src="https://github.com/DonovanDMC/ProjectExpansion/assets/10527873/23c01fcd-6858-4128-9e0d-207625d862f7">

**Minecraft Version**
1.20.1

**ProjectExpansion Version**
1.1.0

**Forge Version**
47.2.32

**Reproduction Steps**
1. Look at advancement menu.
OR
1. Obtain a yellow fuel item/block for the first time

**Comment by DonovanDMC** [comment]
Fixed in [1.1.2](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.20.1-1.1.2)
