### ISSUE TITLE
[BUG]: EMC Link Armor/Tool Import Issue

### ISSUE THREAD

**Issue by rfmineguy** [DonovanDMC/ProjectExpansion#132]
**Description**
EMC Link (of any level) fails to import armor/tool items.

**Minecraft Version**
1.20.1

**ProjectExpansion Version**
1.1.1

**Forge Version**
47.2.0

**Reproduction Steps**
1. Place down an EMC Link
2. Place hopper facing into EMC Link
3. Place helmet (or any armor/tool) into hopper
4. Notice it doesn't go in

**Crash Report/Logs**
N/A

**Other Mods**
ProjectE (1.0.1)

**Comment by DonovanDMC** [comment]
The armor has an NBT value that ProjectE isn't clearing
this is a feature, not a bug
Switch the [nbt filtering mode](https://github.com/DonovanDMC/ProjectExpansion/wiki/EMC-Link#nbt-filtering) if you want it to accept items with nbt

**Comment by rfmineguy** [comment]
Ok. That's my bad for not looking harder. Thank you for the kind reply!

**Comment by rfmineguy** [comment]
Should I rename the issue with [Solved] or is that not required, given that it wasn't a bug at all.

**Comment by DonovanDMC** [comment]
It's fine as is, I use the labels for filtering if needs be
