### ISSUE TITLE
ProjectE, ProjectExpansion, Refined Storage failings

### ISSUE THREAD

**Issue by louisheimza** [DonovanDMC/ProjectExpansion#133]
I am creating a projecte modpack for minecraft 1.20.1 - the newest version projecte supports. I am using the transmutation interface, connected to refined storage with an external data connector. When crafting with the crafting grid, some items are not learnt but the item is inserted into RS instead. 

The external data connector priority is +30 while the RS Hard Disk priority is 0. As expected, most items created in the crafting grid are learnt by projecte when add to the storage. But, for instance some Mekanism items, like the Lapis Lazuli armor or tools are not. It's not just mekanism. For instance I have the same problem with an iron sword. Exact mode on external storage connector is off. But it makes no difference whether on or off.

I have tried to work out what the "pattern" is so that I can remedy it but days later I am no wiser.

Knowing the transmutation interface better than anyone, as the author, do you have any idea why this might be happening? I've been using your mod all along so I am sure it's not broken. I suspect another mod might be breaking it. Do you have any advice on how I can find out what's causing the problem? 

Thanks very much, keep up the good work.

**Comment by GigaOtomia** [comment]
You cannot burn items that can be damaged into EMC using a transmutation interface. You must use a table, tablet, or other original Project E method.

**Comment by DonovanDMC** [comment]
Yes you can, disable nbt filtering
https://github.com/DonovanDMC/ProjectExpansion/wiki/Transmutation-Interface#nbt-filtering

**Comment by louisheimza** [comment]
You beauty genius! Thank you.

 

Sorry I missed this in the documentation.

**Comment by rfmineguy** [comment]
Because this seems like a common question, potentially adding something to the tool-tip of blocks that behave like this explicitly mentioning this functionality in some way might be worthwhile.

**Comment by louisheimza** [comment]
That would be great. Or the old rule applies RTFM – something I missed!
