### ISSUE TITLE
[BUG]: Game hangs when saving while collector is active

### ISSUE THREAD

**Issue by darthvader45** [DonovanDMC/ProjectExpansion#134]
**Description**
When you have a collector feeding a ProjectE Condenser (either mk1 or 2) and save the game, the game hangs.

**Minecraft Version**
1.20.1

**ProjectExpansion Version**
1.1.1 for 1.20.1

**Forge Version**
47.3.3

**Reproduction Steps**
1. Place down a collector connected to a condenser from ProjectE (mine was mk2 for example, with a final collector stuck to it)
2. Save world.
3. Game hangs forever.

**Crash Report/Logs**
N/A

**Other Mods**

![image](https://github.com/DonovanDMC/ProjectExpansion/assets/2816420/ebffc282-9960-402e-8bf7-4c1907ab58b5)

**Comment by DonovanDMC** [comment]
I've finally found the source of this, it seems to be freaking out and getting into an infinite loop when reading a block while saving its data
I'm still not sure exactly why that's causing the problem, but it *is* what's causing the problem
So I'm just going to remove the protection of writing a value larger than our maximum which is causing that read (we already recheck this on load, and there are protections elsewhere) and call it good
https://github.com/DonovanDMC/ProjectExpansion/blob/460c50cf337a6e5464e11f15044d892e55476a24/src/main/java/cool/furry/mc/forge/projectexpansion/block/entity/BlockEntityEMC.java#L224-L226

**Comment by darthvader45** [comment]
Thanks, any fix that can remove this issue is a gamechanger.

**Comment by DonovanDMC** [comment]
Fixed in [1.1.2](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.20.1-1.1.2)
