### ISSUE TITLE
Transmutation interface shows owner as a bunch of zeros, won't connect to any storage interfaces

### ISSUE THREAD

**Issue by Draxinius** [DonovanDMC/ProjectExpansion#135]
![image_2024-07-01_194327012](https://github.com/DonovanDMC/ProjectExpansion/assets/34219478/06571bc2-b72c-4c58-b914-83a74d2ff8e3)
top right in jade, seems to not be registering me as an owner. thing is it was working the last time i launched up the world. no clue what's going on

**Comment by Draxinius** [comment]
small update, seems anything that can be tied to an owner, the power flowers, all of it, has the same error

**Comment by DonovanDMC** [comment]
The bug report template exists for a reason
