### ISSUE TITLE
[BUG]: Matter Upgrader not working on power flowers

### ISSUE THREAD

**Issue by Jester002** [DonovanDMC/ProjectExpansion#136]
**Description**
 Whenever I try to use the matter upgrader to upgrade placed power flowers (i.e. pink to purple) I get red text saying I need to learn the upgraded power flower first, however I have already made another purple power flower and used the knowledge sharing book on it. Possible issue is that the power flowers don't actually have an EMC value so the matter upgrader can not calculate how much EMC it would cost to upgrade and simply does not upgrade it. (Unsure if it's supposed to be this way or not)
**Minecraft Version**
 1.18.2

**ProjectExpansion Version**
 1.1.0
**Forge Version**
 40.2.0

**Reproduction Steps**
 1. place any mini power flower
 2. take matter upgrader
 3. right click power flower
 4. get text saying need to learn upgraded version first 

**Crash Report/Logs**

**Other Mods**

**Comment by DonovanDMC** [comment]
the upgrader item requires both having an emc value
