### ISSUE TITLE
[BUG]: EMC Link stops working when player offline

### ISSUE THREAD

**Issue by Inrixia** [DonovanDMC/ProjectExpansion#137]
**Description**
I am playing with friends on a server. I have emc links setup for our AE2 system. When I disconnect from the server all the items dissappear from the system and it is not possible to input/extract items from the link using pipes/hoppers etc. 

**Minecraft Version**

**ProjectExpansion Version**

**Forge Version**

**Reproduction Steps**
1. Place down an EMC Link connected to external system that pushes or pulls from it 
2. Disconnect from server 
3. Have another player observe the system fail due to the EMC Link no longer functioning or Attempting to push or pull items from the link. 

**Other Mods**
Using mod pack: https://www.curseforge.com/minecraft/modpacks/project-skyq-2

**Comment by DonovanDMC** [comment]
This is working as intended

**Comment by Inrixia** [comment]
So how am I supposed to play with friends?

Edit: Also it would be good if the wiki was updated to reflect this is intended and expected behavior.

**Comment by DonovanDMC** [comment]
I don't know, figure it out? This is a limitation of ProjectE, there is nothing I can do about it

**Comment by Inrixia** [comment]
Does this apply to everything including the transmutation interface?

**Comment by DonovanDMC** [comment]
It applies to anything that touches player emc or knowledge

**Comment by Inrixia** [comment]
Ok, thanks for the quick response!

**Comment by JoBanJo** [comment]
Is there any reason you can't cache a players EMC level and EMC knowledge so when they are offline a server can still access that?

**Comment by DonovanDMC** [comment]
The reason is I have no desire to deal with that, it's complicated to reliably keep up with and if not done exactly right can grossly duplicate emc
