### ISSUE TITLE
[BUG]: advanced alchemical chest not open

### ISSUE THREAD

**Issue by giorgio-modeo** [DonovanDMC/ProjectExpansion#138]
**Description**
Using the modpack "Tekkit the Resurrection 2" with both the item pipes from the "Pipez" mod and the pipe from the "PrettyPipes" mod, the Advanced Alchemical Chest (I mention only this one because everything works correctly with the regular Alchemical Chest) closes immediately after being opened. Additionally, if we use the crafting station from the "Crafting Station" mod, the inventory gets visually duplicated (once another chest is opened, the inventory returns to normal).

**Minecraft Version**

**ProjectExpansion Version**

**Reproduction Steps**

**Other Mods**

** Video of the bug **
https://github.com/user-attachments/assets/33e15f69-233d-46ae-b343-b251c2b30d49
https://github.com/user-attachments/assets/9b8a1ff2-11dc-4a67-b7a6-dba3eca8f251

**Comment by DonovanDMC** [comment]
Fill in the issue template, and provide logs
