### ISSUE TITLE
[BUG]: Alchemical Collection breaks initially "learning" an object

### ISSUE THREAD

**Issue by Xetaxheb** [DonovanDMC/ProjectExpansion#139]
**Description**
I am playing Project Architect 2 pack, I have a Wyvern Pickaxe enchanted with Alchemical Collection (but none of that is probably relevant).

**Alchemical Collection breaks learning anything you don't already have learned, until you "unlearn" it first.**

If I were to mine say End Stone without already having it learned, it will convert to the 1 emc without learning it as expected... but if I try to insert End Stone in a tablet by hand after that, it will consume it without "learning" it. Neither search nor putting in the focus slot will show it. This can be worked around by putting the End Stone in the "unlearn" slot, after which it will be "learnable" again and show up on the right as expected, even if Alchemical Collection is used afterwards.

**Minecraft Version**
1.20.1

**ProjectExpansion Version**
1.1.1

**Forge Version**
47.3.5

**Reproduction Steps**
1. Enchant a tool with Alchemical Collection
2. Break a block that is currently not learned
3. Try and fail to have that block show up in tablet or try and fail to "learn" it

**Comment by DonovanDMC** [comment]
If you leave and rejoin the world, do the items show up in the tablet?

**Comment by Xetaxheb** [comment]
Oops, thought I responded but it didn't go through..

It shows up as learned on rejoin, yes.

**Comment by DonovanDMC** [comment]
Well, it sounds like a simple issue of me forgetting to sync knowledge changes
So at least that should be an easy fix

**Comment by DonovanDMC** [comment]
Fixed in [1.1.2](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.20.1-1.1.2)
