### ISSUE TITLE
Relays don't work

### ISSUE THREAD

**Issue by darthvader45** [DonovanDMC/ProjectExpansion#14]
I connected a relay to a bunch of collectors and a condenser mk2, and tried duping dark matter.  However, no EMC transferred through the relays into the condenser.  So in essence, the relays are non-functional.

**Comment by DonovanDMC** [comment]
I won't be able to look into this for a week at least, as I'm in the process of moving

**Comment by darthvader45** [comment]
That's all right.  I'm available most of the week outside of 9am-2pm Tues-Wed, as those times are when I work at a plant nursery.

**Comment by DonovanDMC** [comment]
I plan on looking into this today (3/15) if possible, and tomorrow otherwise - I don't really have any experience with using relays so this is going to be fun

**Comment by DonovanDMC** [comment]
This has yet again been delayed more, I can't test anything because downloading assets during running the client & even building the jar just is not working anymore because my internet speeds (hotspot) are so bad. I'm getting my internet installed tomorrow, so we'll see then.

**Comment by darthvader45** [comment]
Alright, sounds good.  Wish you the best.  We got ours upgraded just yesterday to fiber from regular copper.

**Comment by DonovanDMC** [comment]
I'm looking into it here, and I have to be honest

I have no clue what these are even supposed to do, as far as I can see they never did anything in ProjectEX either *in the 1.16 version at least*
I'm bordering on just tossing them out, or making them essentially an extension of ProjectE's relays, but faster or more efficient, or something of that nature

**Comment by marekumas** [comment]
As i know Relay gives bonus EMC for collectors. welp u can still use projectEX alpha version they work in there.

**Comment by darthvader45** [comment]
Yeah, as they do the same as ProjectE relays, just once per second instead.

**Comment by DonovanDMC** [comment]
Fixed via #23 

[1.16](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.18)
[1.15](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.15.2-1.0.16)
