### ISSUE TITLE
[BUG]: Deafening audio bug

### ISSUE THREAD

**Issue by LunarBeat** [DonovanDMC/ProjectExpansion#140]
**Description**
When using a vein miner mod, the audio for Alchemical Collection gets exponentially louder as more blocks are broken at the same time.
my ears hurt :(

**Minecraft Version**
1.20.1

**ProjectExpansion Version**
1.1.1

**Forge Version**
47.3.0

**Reproduction Steps**
1.  Turn down block volume
2. Vein mine with alchemical collection
3. Hope you turned down block volume enough or be deafened :(

**Other Mods**
FTB Ultimine
and the rest of the Project Architect 2 pack.

**Comment by DonovanDMC** [comment]
Fixed in [1.1.2](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.20.1-1.1.2)
