### ISSUE TITLE
[BUG]: Tome of knowledge & Transmutation Interface TPS issue

### ISSUE THREAD

**Issue by Xplodin** [DonovanDMC/ProjectExpansion#142]
**Description**

TPS dropped to like 1-3 after learning everything and having a transmutation interface hooked to ae2 system via storage bus
**Minecraft Version**

1.20.1
**ProjectExpansion Version**

1.1.2
**Forge Version**

47.3.0
**Reproduction Steps**

This is a tough one, I guess just hookup a ae2 system to a transmutation interface and learn all knowledge with the tome, and carefully inspect tps
**Crash Report/Logs**

N/A
**Other Mods**

BeanPack: Regurgitated latest version (5.2, modpack)
It seems that once the knowledge was reset/unhooked the interface, tps resumed to a solid 20

**Comment by DonovanDMC** [comment]
Learning every available item is not intended in normal gameplay, I don't think anyone should be surprised when a block which has hundreds of thousands of slots in a single inventory lags
