### ISSUE TITLE
== Feature Suggestions ==

### ISSUE THREAD

**Issue by Kithio** [DonovanDMC/ProjectExpansion#17]
Having been playing with some mods that adds things missing from ProjectEX, there's a few things I'd love to see implemented as well in this.

- EMC-Linked Fuel of some sort, to where it'll pull the equivalent of 1 Coal to restart the burn cycle instead of having to fill numerous sets of coal into a machine or absolutely overkill ones like the 40 months burn time one.

- Integration with Mass Storage Mods such as Refined Storage or Applied Energistics 2, This feature has been quite enjoyable to use as it removes the constant need to run back and forth from Tablet/Table to my crafting menu, and removes need to have all the raw materials stored in my system and can be linked using External Storage and stored in EMC form instead.

The mod that currently adds both of these features is a Helper Mod someone wrote for the modpack "Project Architect" called "Project Architect Additions" - [CurseForge: Project Architect Additions](https://www.curseforge.com/minecraft/mc-mods/project-architect-additions)

That mod also features an infinitely consumable food that drains EMC on consumption but the two things I'd love to see actually added is the EMC-Linked Fuel (EMC Coal) and integration  with mass storage mods like RS and AE2

**Comment by DonovanDMC** [comment]
> or absolutely overkill ones like the 40 months burn time on

I'm planning on doing something about those eventually, not sure what though
I might just make them the same time across the board because it gets way up there way too quick

> something something AE2

I want to do an integration like this but I have no idea how to

As for the infinite fuel bit, that also sounds really interesting

**Comment by DonovanDMC** [comment]
Got a working prototype for two of these suggestions (emc fuel & emc steak (which I've gotten from the aforementioned mod))

![](https://cdn.discordapp.com/attachments/956469600864862228/959333412924166214/ididthething.gif)

Just gotta work out a few kinks here and there and they'll be in the next release

As for the AE2 integration, I still have no idea how to go about that

**Comment by DonovanDMC** [comment]
gotta port this stuff over to 1.15, then I'll make a release & close this

**Comment by DonovanDMC** [comment]
Both mentioned features have been added

Releases:
* 1.15: [1.0.14](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.15.2-1.0.14) (955c1fa7cb9756e6e9570b9737edd99217de2340)
* 1.16: [1.0.15](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.15) (7bb227299f77c9dceef499696f38247c265db8b6, cc4eebe9acf17241fefe5a9d491a96782ec3eb4f)
