### ISSUE TITLE
(...) getStackInSlot is abstract crash 

### ISSUE THREAD

**Issue by DonovanDMC** [DonovanDMC/ProjectExpansion#19]
I cannot tell exactly what this issue is as the method is clearly defined, this is only happening in an instance with many other mods so this may also be an incompatibility with a mod that's causing this. So far I've seen this with pipez, but I suspect it can happen with any mod that has similar functionalities.

As far as I can tell, this effects any tile entity with an inventory, so this is likely something with my implementation
[TileEMCImport Crash](https://pastebin.com/gE0x7Mhb)
[TileEMCExport Crash](https://pastebin.com/VNnT71Uu)

**Comment by etherealgears** [comment]
I'm not sure if this is any help, but I just got this same crash putting a stack of Emerald Blocks into a Hopper connected to an EMC Importer. I was about to post my own issue about it. I don't know anything about coding or such though so no clue why it happened. Does this mean the EMC Importer simply doesn't work at all? I don't know how I'm supposed to import items into my EMC if even connecting a hopper crashes it.

**Comment by DonovanDMC** [comment]
It does work, just some interactions with it aren't working for some reason 

I've already got a minimum reproducible version of this same issue, I just haven't had time to test it

**Comment by DonovanDMC** [comment]
This should be fixed via the changes that have just been made to how things work

[1.16](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.16)
[1.15](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.15.2-1.0.15)
