### ISSUE TITLE
[HELP WANTED] Make the arcane tablet like ProjectEX's version

### ISSUE THREAD

**Issue by DonovanDMC** [DonovanDMC/ProjectExpansion#22]
Their version (in 1.12 at least) has much more functionality than ours, which should be able to be ported over here in some way, shape, or form.

**Comment by VenomsGamer** [comment]
I would love to see that version ported over, I actually have you're mod installed along side the ProjectEX version that isn't ported properly, as long as you'd be able to implement the crafting addition to the gui I think that would be sufficient as that is the main addition that makes the mod super useful in my opinion.

**Comment by DonovanDMC** [comment]
This will probably take a while as I realistically need to write this from scratch as theirs is a jumbled mess, and I don't really want to copy paste code either way

**Comment by darthvader45** [comment]
That's fine.  Hopefully it'll turn out okay.

**Comment by Tarblaz** [comment]
Any news on progress?

**Comment by Kithio** [comment]
Low priority, it'll be released when it's done

**Comment by darthvader45** [comment]
Alright, at least it's something.

**Comment by DonovanDMC** [comment]
I'm closing this as not planned as I do not plan on looking into implementing this any time soon, if at all

If someone else wants to step forward and offer their services in implementing this, I'd be more than happy to work with them
