### ISSUE TITLE
EMC Link Integer Overflow Bug

### ISSUE THREAD

**Issue by James103** [DonovanDMC/ProjectExpansion#27]
As of Project Expansion 1.16.5-1.0.18 for Minecraft 1.16.5, it is possible to get so much EMC so as to make it so the amount of the requested item you can afford rolls past 31 bits, causing a signed integer overflow and the following code to assume you don't have enough EMC since `emc.divide(BigInteger.valueOf(cost)).intValue() < 1`:

https://github.com/DonovanDMC/ProjectExpansion/blob/a7ae6a94033e2a230036fed99acb0ec06607d1de/src/main/java/cool/furry/mc/forge/projectexpansion/tile/TileEMCLink.java#L313-L322

To reproduce:
1. Give yourself a billion EMC: `emc add @s 1000000000`
2. Place down an EMC Link and set it to output stone or any other item worth 1 EMC.
3. Try to take items out of the EMC link.
4. Repeat steps 1-3 until you get a not enough EMC error message.

**Comment by Toshy0** [comment]
Just tested this myself and it does in fact prevent you from taking out the item(in this case im using stone)
![image](https://user-images.githubusercontent.com/87720363/164576148-2cf6e182-2baf-4148-b895-2e57c8bdf5be.png)
![image](https://user-images.githubusercontent.com/87720363/164576172-2f8c608b-4443-4151-8049-655a81a82003.png)
![image](https://user-images.githubusercontent.com/87720363/164576182-e853e29b-0c6a-4446-ba47-982141889a13.png)

**Comment by DonovanDMC** [comment]
Fixed

- [1.16](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.19)
- [1.15](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.15.2-1.0.17)
