### ISSUE TITLE
NBT Filtering

### ISSUE THREAD

**Issue by DonovanDMC** [DonovanDMC/ProjectExpansion#38]
Currently emc links just accept items regardless of emc, if setup without might thought this can toss out things like enchanted items & custom mod items that have emc values

Some kind of item or a gui could be made to toggle a feature for this

**Comment by Kithio** [comment]
Could probably tie in Philosopher Stone to handle this feature, or give the block a UI

**Comment by DonovanDMC** [comment]
if #46 is actually added, it might be smart to add a ui to this block so it can have actual settings and a proper interface, might make the block less confusing to use

**Comment by DonovanDMC** [comment]
extending this issue to cover overall nbt filtering

**Comment by DonovanDMC** [comment]
Added in the latest releases:
- 1.14: [1.0.7](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.14.4-1.0.7) (requires [MixinBootstrap](https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap))
- 1.15: [1.0.26](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.15.2-1.0.26)
- 1.16: [1.0.27](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.27)
- 1.18: [1.0.6](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.18.2-1.0.6)
