### ISSUE TITLE
[1.18.2] Transmutation Interface crashes when used with RS

### ISSUE THREAD

**Issue by Milii20** [DonovanDMC/ProjectExpansion#42]
Greetings!
As the title says, placing the transmutation interface, with an external storage from RS pointing at it, crashes the game with the following crash report:

https://pastebin.com/hwWFtFfC

Thank you very much for your time and for porting the mod to 1.18.2!

**Comment by Kithio** [comment]
This problem has already been fixed and is going to be available in next update.

**Comment by DonovanDMC** [comment]
Fixed in 1.0.1 of 1.18.2

[1.18.2-1.0.1](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.18.2-1.0.1)
