### ISSUE TITLE
Negative EMC totals are not properly formatted

### ISSUE THREAD

**Issue by James103** [DonovanDMC/ProjectExpansion#45]
As of Project Expansion 1.0.1 for Minecraft 1.18.2, when you have a large negative amount of EMC, the number is not properly formatted.

To reproduce:
1. Create a new world with cheats enabled.
2. `emc set @s 0`
3. `emc remove @s 123456789000`
4. Give yourself a Transmutation Tablet.
5. Notice that the EMC in the top left corner is not formatted, and the text that is supposed to display your available EMC in the tablet shows `-0 Trillion`.

See also #16

**Comment by DonovanDMC** [comment]
This might be fixed in the future, but currently I have no plan to fix it
many other features are taking priority

**Comment by DonovanDMC** [comment]
The specific method of causing this will be fixed in the next update, but I'm still not planning on making an effort to properly format any negative values

Especially as you cannot load a world with negative emc, ProjectE will crash while loading
