### ISSUE TITLE
crash on server when someone in creative places and clicks them selves to a mk 15 solar flower

### ISSUE THREAD

**Issue by SDUBZ** [DonovanDMC/ProjectExpansion#48]
forge 1.18.2-40.1.19
projecte exp: ProjectExpansion-1.18.2-1.0.2
crash report:
[crash-2022-05-10_07.54.18-server.txt](https://github.com/DonovanDMC/ProjectExpansion/files/8662682/crash-2022-05-10_07.54.18-server.txt)

**Comment by DonovanDMC** [comment]
Update to the latest release.
