### ISSUE TITLE
Infinite steak does nothing

### ISSUE THREAD

**Issue by Agentx49** [DonovanDMC/ProjectExpansion#49]
I crafted the infinite steak but when I right click nothing happens and I'm still hungry

**Comment by DonovanDMC** [comment]
do you have any available emc

the amount you need is equivalent to whatever a normal steak is worth

**Comment by DonovanDMC** [comment]
I'll be closing this tomorrow if I don't hear back from you

**Comment by Agentx49** [comment]
yeah I had a ton of EMC

**Comment by DonovanDMC** [comment]
going to need more info than "it doesn't work"

Version, mod version, other mods, etc.

**Comment by Agentx49** [comment]
ProjectExpansion-1.18.2-1.0.3

modpack: https://www.curseforge.com/minecraft/modpacks/project-spacee

**Comment by DonovanDMC** [comment]
unless you can reproduce the issue without other mods present, I'll be considering this a mod compatibility issue and will then consider it a non-issue

**Comment by Agentx49** [comment]
just reproduced it with only project expansion and project e installed

**Comment by Kithio** [comment]
Fixed in upcoming patch

**Comment by DonovanDMC** [comment]
Fixed in [1.0.5](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.18.2-1.0.5)
