### ISSUE TITLE
Idea: Per-tier configuration of EMC generators, links, and power flowers

### ISSUE THREAD

**Issue by James103** [DonovanDMC/ProjectExpansion#50]
Currently, almost all of the EMC related stats for the new blocks and items added by the mod are hard-coded, including:
* The per-second EMC generation for collectors.
* The per-second EMC transfer rate and bonus for relays.
* The per-second EMC generation multiplier for power flowers.
  - This is currently configurable globally, but not per-tier.
* The per-second EMC limit for EMC Links.
* The per-second item I/O limit for EMC Links.

With the default values being proportional to O(n!) in the tier of the block, the scaling may be too harsh and some modpacks may want to nerf the higher tiers, while leaving the lower tiers untouched. On the other hand, a modpack may make each tier cost a lot more EMC than the last, to the point where the total cost quickly outpaces the default values.

I propose adding the following six lists to the config, one for each of the seven values, with one entry per tier starting at tier 1 and going through the final tier:
* Collectors - Production rate (EMC/s)
* Relay - Max transfer rate (EMC/s)
* Relay - Bonus rate (EMC/s)
* Power Flower - Multiplier (EMC/s)
  - The actual generation rate is derived from the production and bonus rates for the collectors and relays respectively.
* EMC Link - Max EMC import limit (per second)
* EMC Link - Max item I/O limit (per second)

Ideally, the values in the new config options should be able to support numbers up to 1.79769&times;10<sup>308</sup>.
If that's not possible, the next best upper limit is 2<sup>63</sup>-1 &approx; 9.223 quintillion.

**Comment by DonovanDMC** [comment]
I'm absolutely *not* going to make a config option for every single tiered block, at best you're getting a multiplier
powerflowers already have this and I have no plans to spread this to other blocks

something will eventually be done about the scale of emc gain from blocks
