### ISSUE TITLE
Transmutation Interface still crashing on player death?

### ISSUE THREAD

**Issue by tekacs** [DonovanDMC/ProjectExpansion#56]
After updating to 1.0.7 from 1.0.5, I'm sadly still seeing a server crash when the player behind a Transmutation Interface dies.

In this case I'm extracting items with LaserIO as you can see -- and this works smoothly except when the player dies.

[crash-2022-06-05_22.19.02-server.txt](https://github.com/DonovanDMC/ProjectExpansion/files/8841422/crash-2022-06-05_22.19.02-server.txt)

**Comment by DonovanDMC** [comment]
Still blaming ProjectE for this, give me 10 or 15 minutes

**Comment by DonovanDMC** [comment]
This specific bug should be fixed in [1.0.8](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.18.2-1.0.8), I have the sinking feeling this is going to be a recurring issue

**Comment by tekacs** [comment]
Thank you @DonovanDMC, that looks to be the last NPE on death at least in my use -- even with power flowers + transmutation interfaces down, death no longer crashes the server.

I'm with you on [the location in ProjectE](https://github.com/sinkillerj/ProjectE/blob/e157c774a22019cdccc73f896cb4e4c13503e543/src/main/java/moze_intel/projecte/impl/TransmutationProxyImpl.java?rgh-link-date=2022-06-02T12%3A46%3A30Z#L37) that you pointed out. Iit feels like it's only been 'safe' for them because ProjectE interactions are all (?) interactive, so they can't run into an issue where the player is dead but they still need the KnowledgeProvider? It doesn't seem like that API design (throwing an NPE there) wil ever work in a case where a block tick demands it with that value unavailable triggering an NPE. :/

**Comment by Avi-E-Koenig** [comment]
is it possible to simply void emc while player is dead?
