### ISSUE TITLE
[Question] Matter Recipes Included?

### ISSUE THREAD

**Issue by MonfGeiger** [DonovanDMC/ProjectExpansion#63]
its nice to see ProjectEX has a forked being maintained for newer minecraft versions. im currently exploring the other items of the ProjectEX mod in StoneBlock 2 and see these power flower blocks that have different versions of collectors and all that, which need different colored matter items that in ProjectEX/SB2 have no concrete recipe

if I ever play a modpack that either has this fork included or that I can shove this in a modpack of my choosing that won't error-crash me out, can I assume that this mod also includes recipes on how to obtain the differing states of matter, and if so, how do I craft them?

**Comment by DonovanDMC** [comment]
Use jei for recipes
