### ISSUE TITLE
Infinite Steak / Coal should check that their base items have EMC values before working

### ISSUE THREAD

**Issue by James103** [DonovanDMC/ProjectExpansion#64]
Currently, when Infinite Coal is placed in a furnace while Coal has no EMC value, or Infinite Steak is eaten while Steak has no EMC value, the item works, but the player's EMC is not adjusted.

This may cause balancing issues, especially as the former can result in infinite furnace fuel (and FE with other mods) at no ongoing cost, while the latter may effectively result in the player being able to eat for free.

Issue exists since 7bb227299f77c9dceef499696f38247c265db8b6, so any version of Project Expansion that has the Infinite Fuel and Infinite Steak should be able to reproduce this.

To reproduce:
1. Remove the EMC value from Coal (`minecraft:coal`) and Steak (`minecraft:cooked_beef`).
2. Give yourself the Infinite Coal, Infinite Steak, any smeltable item such as cobblestone, and a furnace.
3. Place down the furnace and place the Infinite Coal in its fuel slot.
4. Place any smeltable item in the same furnace.
5. Make yourself hungry: `effect give @s hunger 2 255`
6. Try eating the Infinite Steak.
7. If hunger is restored after eating, the Infinite Steak worked for free.
8. Check the furnace.
9. If the furnace successfully smelted an item, the Infinite Coal worked for free.

**Comment by DonovanDMC** [comment]
I'm conflicted between defaulting to their "normal" emc value and disabling the items
I might go and add a config option instead so they don't rely on external values

**Comment by DonovanDMC** [comment]
went the config option route, now the cost of both & the burn time of the fuel is configurable

release time is unknown, it'll happen when I either bring around more features or this sits around for long enough to be pushed out on its own

**Comment by DonovanDMC** [comment]
Fixed in latest releases
1.15: [1.0.31](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.15.2-1.0.31)
1.16: [1.0.32](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.32)
1.18: [1.0.12](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.18.2-1.0.12)
