### ISSUE TITLE
Matter upgrader not working

### ISSUE THREAD

**Issue by AmsterDamian** [DonovanDMC/ProjectExpansion#65]
I have made an matter upgrader, the description says I need to learn the next tier. So I made the next tier with the hand but when I want to upgrade my other collectors it still says I need to learn the next tier. I have 58 million EMC so that cant be the issue. How does this item work?

**Comment by DonovanDMC** [comment]
Have you actually learned the item, i.e. put it into your transmutation table? You need to have knowledge of it

**Comment by AmsterDamian** [comment]
I have the matter in the table, but I cant add the collectors to the table

**Comment by DonovanDMC** [comment]
the upgrader requires the next tier item to be in your knowledge

**Comment by AmsterDamian** [comment]
The collectors dont have EMC, so how can I add those to my knowledge?

**Comment by DonovanDMC** [comment]
They do in normal gameplay, so something you're using is changing that

**Comment by AmsterDamian** [comment]
Do you have any idea what it can be? The relays do have EMC but only the collectors dont

**Comment by DonovanDMC** [comment]
No. Look in to any other mods you're using, and ProjectE's custom emc values.

**Comment by AmsterDamian** [comment]
Okay, I'll look into it. Thanks for the help and fast reply
