### ISSUE TITLE
[1.0.31] EMC (Item) Links Reporting Incorrect Number of Items

### ISSUE THREAD

**Issue by Timeslice42** [DonovanDMC/ProjectExpansion#66]
Version .31 is not reporting the correct number of items for EMC links to other storage mods (such as AE2). In version .26 (or maybe it was .24?) the link would report the amount as the number of items that could be supplied given your current EMC. While not correct, it was at least usable. In the current version it is always reporting the amount as 1, which is definitely not usable for automated crafting.
Specifically, in my case, I'm using an AE2 storage bus on an EMC (item) Link.

Ideally the reported value should be the lesser of TotalEMC/ItemEMC or the item limit for the EMC Link in question.

The Transmutation Interface seems to be working fine.

[Edit] The version of AE2 did not change between these two scenarios.

**Comment by DonovanDMC** [comment]
The emc link isn't what should be connected to the storage bus, that's the Transmutation Interface. The emc link *is* reporting an incorrect inventory count, that will be fixed, but it will take a while to make it into a release.

**Comment by Timeslice42** [comment]
If I could craft the transmutation interface I'd obviously be using the interface. :P
Rolling back to .27, the version before Fluid Links should fix the issue, right?

**Comment by DonovanDMC** [comment]
I.. wouldn't really recommend purposely downgrading, especially that far, but sure

This came from some code cleanup in 1.0.28
https://github.com/DonovanDMC/ProjectExpansion/commit/d7c990b3d7a41ccf6d4a93463acb608a0e6ea61d#diff-22fc7281f10f979f36281bff93afd19635b9ef30c779bceeafdc6f5c3554c8ccR190

You'll be missing out on these, and more
- emc link fluid handling
- another bug with emc links that was fixed in [1.0.29](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.29)
- the alchemical collection enchantment
- the knowledge sharing be

**Comment by Timeslice42** [comment]
Yeah, as it stands half of my auto-crafting is busted, so my choices are re-engineer the whole thing, or roll back to the version that I was using up until my previous session. Since I'm maybe 20 hours away from being able to craft the transmutation interface, re-engineering a system that's going to be replaced didn't appeal to me.
I'll definitely be returning to latest once I do that though. Thank you for your help!

**Comment by DonovanDMC** [comment]
If you don't mind running a dev build, I could whip one of those up quickly

it shouldn't be noticeably different, but I won't be publishing a new version for at least another week or until another bug comes through

**Comment by Timeslice42** [comment]
That would be just fantastic. Are we talking tons of log spam, or just a version I'll have to manually install as opposed to using curseforge?

**Comment by DonovanDMC** [comment]
Should just be the latter, it's still a normal build, just tagged differently

**Comment by Timeslice42** [comment]
I'm off now, but I'll check this issue again in the morning. Thanks for helping me out.

**Comment by DonovanDMC** [comment]
Build's been made, it'll be shown as `1.16.5-1.0.32-dev.20220723a`

I can't attach jars here, so I've uploaded it under a directory on one of my sites
https://furry.cool/tmp/ProjectExpansion-1.16.5-1.0.32-dev.20220723a.jar

do note that any bugs noticed with this version *should* be reproduced in a non-development version before reporting

**Comment by DonovanDMC** [comment]
Fixed in latest releases
1.15: [1.0.31](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.15.2-1.0.31)
1.16: [1.0.32](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.32)
1.18: [1.0.12](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.18.2-1.0.12)
