### ISSUE TITLE
[enhancement] support for equipping magnum and colossal stars in the curios klein star slot

### ISSUE THREAD

**Issue by NyanMC** [DonovanDMC/ProjectExpansion#67]
i asked about this over discord, and you suggested that i open an issue about it
![image](https://user-images.githubusercontent.com/44331238/182009284-c504c195-dbd9-4f4a-abba-a7cb9c3abd82.png)

**Comment by DonovanDMC** [comment]
This is technically both a bug and a suggestion as this was meant to happen at some point, but never did

**Comment by DonovanDMC** [comment]
I actually *did* start implementing this, it turns out I just didn't finish it

Does the item just go in there or is there some further usage I can test
![image](https://user-images.githubusercontent.com/17226394/182070570-69305f68-e481-49f3-bcad-d6169615f04c.png)

**Comment by NyanMC** [comment]
to be honest i'm not quite sure what else it does, if anything
taking a glimpse at the code makes it seem that equipping the klein star in a curio slot just makes it work the same way it does in the inventory, just from the curio slot

**Comment by DonovanDMC** [comment]
in theory if they do anything else, that should be included as I've used ProjectE's capability
https://github.com/DonovanDMC/ProjectExpansion/blob/10098f4cd56ac0dbc6d097b440373f4d2e0f9332/src/main/java/cool/furry/mc/forge/projectexpansion/item/ItemMagnumStar.java#L37-L38

So I'm considering this as complete, and I'll probably get it into a release today

**Comment by DonovanDMC** [comment]
Fixed in latest releases
1.15: [1.0.31](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.15.2-1.0.31)
1.16: [1.0.32](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.32)
1.18: [1.0.12](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.18.2-1.0.12)
