### ISSUE TITLE
crash with blue emc link

### ISSUE THREAD

**Issue by Xplodin** [DonovanDMC/ProjectExpansion#68]
[crash-2022-08-03_12.46.55-server.txt](https://github.com/DonovanDMC/ProjectExpansion/files/9255448/crash-2022-08-03_12.46.55-server.txt)

It makes it so the world is unable to load

**Comment by DonovanDMC** [comment]
Any information besides "it crashed" and a report would be just lovely
I need to be able to reproduce this to be able to fix it

**Comment by Xplodin** [comment]
My bad was in a hurry. It crashes when theres an overflow with mekanism logistical transport pipes attached to a blue emc link

**Comment by DonovanDMC** [comment]
Considering this as unactionable as I cannot reproduce it, if you can reproduce this with as few mods as possible, or provide a more detailed way to reproduce the issue, I'll consider it.

The version you're using is also [outdated](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.18.2-1.0.12)
