### ISSUE TITLE
[1.16.5]Multiplayer Log Spam "EMC/maxPer"

### ISSUE THREAD

**Issue by 1keponchem** [DonovanDMC/ProjectExpansion#69]
[console.log](https://github.com/DonovanDMC/ProjectExpansion/files/9283449/console.log)
(redirected from stdout)

As shown above, the log on server is spammed by lines of "[EMC/maxPer] \<some random number> null"
This only happens when any type of collector/relay from ProjectExpantion is placed in world, and the number of lines per seconds are same as the number of those blocks. So, when many of them are placed in world, the server's disc is overwhelmed and eventually it breaks.
the numbers in lines are possibly linked to emc generation.

This phenomenon is not recorded on latest.log.

**Comment by DonovanDMC** [comment]
Update to latest.
