### ISSUE TITLE
EMC Display On HUD

### ISSUE THREAD

**Issue by DonovanDMC** [DonovanDMC/ProjectExpansion#7]
Just like ProjectEX had in 1.12, I plan on trying to port over their whole gui bit for displaying emc & gained emc in the top right of the screen. I'm still pretty new with this stuff, so getting this to work might take a while.

**Comment by DonovanDMC** [comment]
added in 36d189175f32f6b94b4274074ed27748122c9438

**Comment by Milkman-Mike** [comment]
is there a way to get rid of the display since i have my always show fps thing there and kinda need to see how much emc i have in the table

thanks

**Comment by DonovanDMC** [comment]
> is there a way to get rid of the display since i have my always show fps thing there and kinda need to see how much emc i have in the table
> 
> thanks

There's a config option for it
If you're on the 1.21 version you can also change its position

**Comment by Milkman-Mike** [comment]
where theres no mod config option im on neoforge
