### ISSUE TITLE
Causes world-loading deadlock when installed alongside Dragon Survival

### ISSUE THREAD

**Issue by tlitookilakin** [DonovanDMC/ProjectExpansion#70]
[Log](https://mclo.gs/Onp8AMb) demonstrating the problem on a minimal installation. (GeckoLib, Dragon Survival, ProjectE, Project Expansion).
It seems to be causing reflection errors- first crashing dragon survival, and then preventing the server from shutting down correctly, leaving the game to hang.

**Comment by DonovanDMC** [comment]
We are not mentioned in the error log. Report the issue to them.

**Comment by tlitookilakin** [comment]
I know it's not in the trace, but adding and removing this mod causes the crash or prevents it, even in very large packs with many other mods. this mod is definitely at fault. Dragon Survival does not have this problem with _any other_ mod.

**Comment by DonovanDMC** [comment]
If this is on our side, I'm not willing to look in to it.
