### ISSUE TITLE
Game is gone when i do this

### ISSUE THREAD

**Issue by Sanzelize** [DonovanDMC/ProjectExpansion#72]
if i connect a cable to **Transmutation Interface** its starting putting items to chest or drawer its doing the job but when i open the **Transmutation Tablet** game become frozen and not responding i waited like 30 min. and nothing happened so i closed the game, i think if i use over 2 billion emc this happens i don't know maybe it can be a unfixable issue

**Comment by DonovanDMC** [comment]
I need more info than "it doesn't work fix it"

What version, are you using any other mods, what's happening in the world, etc

You also need to reproduce it without any extra mods in a world that doesn't have anything major happening in the background before I'll look into this

**Comment by Sanzelize** [comment]
version is ProjectExpansion-1.18.2-1.0.11 and ProjectE-1.18.2-PE1.0.1 
https://imgur.com/a/RVkbKpH this is the system i use and pipe transports this much item https://imgur.com/a/lf5MUe2
and thats is my mod list: https://pastebin.com/7sLw3bHL
forge version: 40.1.74
and im using atm 7 modpack **atm7 0.4.30** version, i just added some mods to pack if u need more information i can upload save and the pack gdrive

**Comment by KirikaAetheria** [comment]
I saw the RFTools Builder on your mod list, were you by any chance using the Builder at the time? I've noticed this bug while using an EMC Link to output items directly into the Builder while it performs a task. The game will be perfectly normal unless you open the tablet, at which point there is a massive FPS drop, aggravated further if you type anything into the search bar, and can even freeze completely and force a reset

If that's what you're experiencing, try turning the builder off before opening the tablet. That should circumvent the problem until a fix comes out

**Comment by Sanzelize** [comment]
uh thank u i'll try that

**Comment by DonovanDMC** [comment]
I need either a step-by-step reproduction list, or a world download with exact instructions on what to do

I would also love a minimal reproduction environment as I cannot realistically test with that many mods in a development environment
