### ISSUE TITLE
Request of configuration options.

### ISSUE THREAD

**Issue by Normal69** [DonovanDMC/ProjectExpansion#73]
Hello!

I'm glad you did this one. Using: ProjectExpansion-1.18.2-1.0.12.jar
Previously I've used the old ProjectEX to tone down greatly power-flower and collector input, so encourage more clever solutions by hidden loops and such. The old config is here: https://pastebin.com/W9HEahDJ

Together with ProjectE set to 1/5 value and rounding down, that removed huge cobblestone makers, made the player think rather crafting than simply getting an item out from EMC, and a general building material helper.

Looking at the config here I'd be grateful if I'be able to set these multipliers to a fraction number, like "0.2":
collectorMultiplier = 1
emcLinkItemLimitMultiplier = 1
emcLinkFluidLimitMultiplier = 1
emcLinkEMCLimitMultiplier = 1
powerflowerMultiplier = 1
relayBonusMultiplier = 1
relayTransferMultiplier = 1

Plus if there'd be a switch which disables crafting the old collectors and relays, the game would be lesss laggy as EMC would be added by seconds and not by ticks.

These changes would raise this mod again to the sorrow of all EMC users, and as you know, the success of a server needs player-tears.
(also make EMC an useful tool instead breaking most other mods depending on resources)

Thank you kindly, and have a fun weekend!

(ps: do you know a mod which connests EMC to the Building Gadget for 1.18.2?
https://www.curseforge.com/minecraft/mc-mods/emcgadgets )

**Comment by DonovanDMC** [comment]
Implementing this now, this will definitely result in some values being zeroed out, but I'm going to leave people may want that

Original Values:
![image](https://user-images.githubusercontent.com/17226394/193355504-eb9ff710-d647-48ee-897b-88ed34b10a0b.png)

0.2:
![Screenshot from 2022-09-30 15-57-22](https://user-images.githubusercontent.com/17226394/193355524-17b1d4d5-355c-48d5-8536-15d57b7212b7.png)

It's rounded down as fractional emc isn't a thing, and I'm not about to handle decimals


Included Options:
* `collectorMultiplier`
* `emcLinkItemLimitMultiplier`
* `emcLinkFluidLimitMultiplier`
* `emcLinkEMCLimitMultiplier`
* `powerflowerMultiplier`
* `relayBonusMultiplier`
* `relayTransferMultiplier`

**Comment by DonovanDMC** [comment]
Added in latest versions
1.15: [1.0.32](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.15.2-1.0.32)
1.16: [1.0.33](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.33)
1.18: [1.0.13](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.18.2-1.0.13)
1.19.2: [1.0.1](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.19.2-1.0.1)
