### ISSUE TITLE
Upgrade tool and ownership are wonky in Singleplayer

### ISSUE THREAD

**Issue by adamkad1** [DonovanDMC/ProjectExpansion#75]
When i used the matter upgrader on an EMC link in SP world, and tried to interact with it afterwards the game told me 'You do not own this,  does.'

**Comment by adamkad1** [comment]
It seems like loading an SP world jumbles up the ownership data of things as far as the upgrader is concerned. When I place a flower, I can upgrade it just fine, but after loading the world, attempting to upgrade a flower that was there tells me 'You do not own this'. It still shows my name when right clicked though. And things still seem to properly output EMC into my 'bank'

**Comment by loldev69** [comment]
For EMC links, the bug appears to happen immediately, and not on world reload.
Steps to reproduce:
1.  put down a collector
2. set an export item
3. upgrade the collector
4. right click the collector to retrieve items 

And you'll get the ownership error message.

**Comment by DonovanDMC** [comment]
Why it's giving the user hell is a mystery to me, as the data looks the same, but I do know what I'm missing
there's a desync somewhere in here I feel

It seems the client knows the correct data (even after a world reload), but the server sees it differently
dunno, something's funky here
![image](https://user-images.githubusercontent.com/17226394/198523435-e8510bda-9107-46c5-8f43-5fc20a0541ac.png)
Data matches yet the first errors
I'll have a release to fix that soon

**Comment by DonovanDMC** [comment]
Fixed in latest releases
1.15: [1.0.33](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.15.2-1.0.33)
1.16: [1.0.34](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.34)
1.18: [1.0.14](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.18.2-1.0.14)
1.19.2: [1.0.2](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.19.2-1.0.2)
