### ISSUE TITLE
Linkable Chest With Alchemical Bag

### ISSUE THREAD

**Issue by DonovanDMC** [DonovanDMC/ProjectExpansion#76]
As the title says, a chest which can be click on with an alchemical bag, which will then link the two

**Comment by ThatOneDevil** [comment]
Check the code on how ender chests work and try to use that with alchemical bags?

**Comment by ThatOneDevil** [comment]
> Check the code on how ender chests work and try to use that with alchemical bags?

I mean the ender chest from the ender chest mod not vanilla ones

**Comment by DonovanDMC** [comment]
![image](https://user-images.githubusercontent.com/17226394/200206759-cea42777-25ad-4829-b9b3-3041e49fa080.png)
I've actually finally gotten into this and I think I've got it done

**Comment by ThatOneDevil** [comment]
Looks sick, these would be linked to alchemical bags right? you might also want to add a private system and maybe more colour like the ender chests

**Comment by DonovanDMC** [comment]
They're similar in color to fit the aesthetic of ProjectE

**Comment by DonovanDMC** [comment]
Added in latest versions
