### ISSUE TITLE
Crash on Death - EMC link with item export in world

### ISSUE THREAD

**Issue by TheLastCreation** [DonovanDMC/ProjectExpansion#77]
single player (haven't tested multiplier) minecraft crashes when the player dies if you have an EMC link down that has an export target set

[crash-2022-10-21_12.07.40-server.txt](https://github.com/DonovanDMC/ProjectExpansion/files/9841910/crash-2022-10-21_12.07.40-server.txt)

mods installed;
ProjectE-1.18.2-PE1.0.1.jar
ProjectExpansion-1.18.2-1.0.13.jar

forge version:
40.1.73

**Comment by DonovanDMC** [comment]
Attach the actual crash report

**Comment by TheLastCreation** [comment]
[crash-2022-10-21_12.07.40-server.txt](https://github.com/DonovanDMC/ProjectExpansion/files/9841910/crash-2022-10-21_12.07.40-server.txt)

**Comment by KuroPeach** [comment]
Multiplayer also crashes
[crash-2022-10-21_11.46.22-server.txt](https://github.com/DonovanDMC/ProjectExpansion/files/9844228/crash-2022-10-21_11.46.22-server.txt)

**Comment by Kithio** [comment]
Looked into it a bit, and from what I can see it's crashing on a ProjectE function and not a ProjectExpansion function, no idea why it happens as it shouldn't by how their code is written

**Comment by DonovanDMC** [comment]
I've talked to them, it's due to how forge works
Fetching capabilities fails when the player is dead

#56 & #52

I called it in #56, this will be a recurring issue

ProjectE can't really do anything but throw as the method return is not nullable

**Comment by DonovanDMC** [comment]
[Discord Message](https://discord.com/channels/400439566302969857/400439566302969861/983207870281699358)

**Comment by Avi-E-Koenig** [comment]
can confirm issue on MP aswell.

**Comment by AmmoniumX** [comment]
Is the issue then fixable or not, due to the Forge behaviour?

**Comment by DonovanDMC** [comment]
Fixed in [1.0.14](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.18.2-1.0.14)
