### ISSUE TITLE
Division by zero extracting items from EMC Link using Pipez item pipes

### ISSUE THREAD

**Issue by James103** [DonovanDMC/ProjectExpansion#83]
The following line may crash if the EMC value for the `ItemStack` passed in is zero.
https://github.com/DonovanDMC/ProjectExpansion/blob/c18e16de0f052a05af17a87db736eece3b7232c2/src/main/java/cool/furry/mc/forge/projectexpansion/block/entity/BlockEntityEMCLink.java#L191

To be more specific, if `ProjectEAPI.getEMCProxy().getValue(itemStack)` returns zero, then the division in the above line tries to divide a BigInteger value by zero, throwing `java.lang.ArithmeticException: BigInteger divide by zero` and crashing the game.

Fixing this will likely need a guard that checks if `ProjectEAPI.getEMCProxy().getValue(itemStack)` is zero, and if so returns `ItemStack.EMPTY` (i.e. no item).

See also https://github.com/AllTheMods/ATM-8/issues/811

**Comment by DonovanDMC** [comment]
Fixed in [1.0.6](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.19.2-1.0.6)
