### ISSUE TITLE
Personal EMC link generates items with original item's NBT data 

### ISSUE THREAD

**Issue by TheDyreBanana** [DonovanDMC/ProjectExpansion#84]
When using a personal EMC link with items that store stuff they will generate more of that item with that stuff in it. If you place a drawer of 64 fading matter it will give you drawers full of 64 fading matter. 

version: 1.19.2-1.0.4

**Comment by DonovanDMC** [comment]
Fixed in [1.0.7](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.19.2-1.0.7)
