### ISSUE TITLE
EMC Link only exporting one item while taking more emc

### ISSUE THREAD

**Issue by Sixdd6** [DonovanDMC/ProjectExpansion#86]
So I tried with Refined Pipes and with LaserIO and cannot get the Magenta EMC Link to allow more than one item to be extracted at a time. The tooltip says it allows 8/s. May be a good idea to check the other emc links as well.

[latest.log](https://github.com/DonovanDMC/ProjectExpansion/files/10608311/latest.log)

**Comment by DonovanDMC** [comment]
I've tested it myself and it works fine with pipez. Unless you can provide a more specific set of reproduction steps I'm considering this a non-issue.

**Comment by Sixdd6** [comment]
Specific steps to reproduce:
1. Grab an EMC Link Mk2, or Mk3, or Mk4 or any of them.
2. Place the Link and set it to an output, specific output doesn't matter.
3. Set a pipe to pull from the Link and input into a chest, or a machine, or a black hole, it doesn't really matter.
4. Observe that the Link only outputs a single item at a time rather than its advertised rate.

I've tested now with Refined Pipes, LaserIO, and setting a Thermal Expansion machine to auto-pull from the Link directly. Every instance resulted in only a single item being received at the output at a time. If I'm misunderstanding how the Link works then I'd appreciate being educated in that matter as the tooltip leads one to believe that it should extract multiple items at once.

I can appreciate that you test against Pipez specifically however I would think you'd want more compatibility in the ecosystem.

**Comment by DonovanDMC** [comment]
Knowing the same emc was being removed while the number of items was incorrect would have been great

**Comment by Sixdd6** [comment]
I feel like there is some misunderstanding here. I went ahead and tested with Pipez and while it does indeed "work", it only works because of the way that specific mod pulls items. The pipez mod seems to pull items every tick, grabbing everything that it is allowed at each tick. This has taught me that your mod allows only a single item to be extracted every tick, rather than the expected behavior of allowing up to it's max items per second all at once. In short, I was expecting the various pipes from these other mods to be allowed to pull the max items per second each operation but because the EMC Link only allows a single item per operation this is impossible.

In the case of Laser IO I tested with a node attached to a Mk4 Link and a chest on the other side. The node is set to pull 8 items every 20 ticks, however the observed behavior results in only a single item being pulled every 20 ticks. I hope this makes it more clear what I was trying to accomplish. Please let me know if you need more information before closing the issue.

**Comment by Sixdd6** [comment]
Sorry to post again so soon. After some more testing it does seem that I was indeed misunderstanding the way the Links operate. I used a LaserIO node again and this time set it to pull every tick and it does indeed pull much faster. I believe it may help in the future to reword the tooltips to read in items per tick. However my original issue is now resolved, thank you for your assistance.

**Comment by DonovanDMC** [comment]
it isn't items per tick, it's per second
you weren't reading anything wrong

**Comment by DonovanDMC** [comment]
as I said, knowing the correct emc was being removed but the incorrect item count was being returned would have been really useful as that's exactly where the problem is

The returned stack size was one no matter what was requested, so if something requested more than one the rest of the emc was just voided

**Comment by DonovanDMC** [comment]
This has been fixed in [1.0.20](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.18.2-1.0.20).

**Comment by Sixdd6** [comment]
Ah I see, in my testing I wasn't watching the emc values very closely so I missed that. Thank you again :)
