### ISSUE TITLE
[BUG]: Cannot export fluid with Final EMC Link 

### ISSUE THREAD

**Issue by raybin7** [DonovanDMC/ProjectExpansion#88]
**Description**

I tried to export water with EMC Link, other EMC link(Fading EMC Link, in screenshot) worked, but Final EMC Link doesn't work.

![2023-03-21_16 18 19](https://user-images.githubusercontent.com/85476966/226541041-22ec07ab-3344-473e-aff8-91f880f8e3e3.png)
![2023-03-21_16 18 23](https://user-images.githubusercontent.com/85476966/226541048-d2bc44c6-c387-4717-a66e-2df1a6efa910.png)

When I set export item a water bucket, Fading EMC link works as water tank, so jade shows water 16.38kB, but Final EMC Link shows "empty"

**Minecraft Version**

1.19.2
**ProjectExpansion Version**

1.0.8
**Forge Version**

43.2.0
**Reproduction Steps**

1. Set a water bucket as export item in Final EMC link
2. I can get water bucket item from Link, but cannot export water as fluid

**Crash Report/Logs**

**Other Mods**
<-- Any other mods you had enabled when you noticed the issue. Please try to reproduce the issue with as few mods as possible so we can test/reproduce the issue easier. You can skip this step if you've attached a crash report. -->

**Comment by DonovanDMC** [comment]
Fixed in [1.0.10](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.19.2-1.0.10) for 1.19.2

**Comment by DonovanDMC** [comment]
1.18: [1.0.21](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.18.2-1.0.21)
1.16: [1.0.41](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.41)
