### ISSUE TITLE
[SUGGESTION]: Add the "projecte:collector_fuel" tag to your fuel types

### ISSUE THREAD

**Issue by HarbingerOfCrazy** [DonovanDMC/ProjectExpansion#89]
While playing the Mechanical mastery modpack i noticed that you higher Emc fuel types are incompatible with ProjectE's EMC consuming items, like the Swiftwolf's rending gale.
After some fiddling with kubejs I found that adding the "projecte:collector_fuel" tag to them fixes this.
Though it might cause some issues with collectors, idk they are disabled in the modpack.

Additionally having the infinite fuel do the same directly from your stored EMC (in increments equal to it's configured value) would be neat, or better yet a way to fuel them directly without having to lug around a stack of alchemical fuel.

**Comment by DonovanDMC** [comment]
Done in [1.0.10](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.19.2-1.0.10) for 1.19.2

**Comment by DonovanDMC** [comment]
1.18: [1.0.21](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.18.2-1.0.21)
1.16: [1.0.41](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.41)
