### ISSUE TITLE
Transmutation Interface does not save items with NBT

### ISSUE THREAD

**Issue by AviKohn7** [DonovanDMC/ProjectExpansion#90]
If an item has NBT data that is not the default NBT data, it will not be saved using the Transmutation Interface. This is most likely so the NBT isn't lost through saving (because the actual item would be deleted otherwise). However, it would be nice to still _save_ the item as knowledge, but just not remove it from the storage system.

To solve this, just change:
https://github.com/DonovanDMC/ProjectExpansion/blob/5e109a8879b69c6bc718062f5d5e3c925b424735/src/main/java/cool/furry/mc/forge/projectexpansion/block/entity/BlockEntityTransmutationInterface.java#L109
To something like:
```
if(getFilterStatus() && !NBTManager.getPersistentInfo(info).equals(info)) {
    @Nullable IKnowledgeProvider provider = Util.getKnowledgeProvider(owner);
     if(provider == null) return stack;
     ServerPlayer player = Util.getPlayer(level, owner);
     if (player != null) {
         if (provider.addKnowledge(stack)) provider.syncKnowledgeChange(player, NBTManager.getPersistentInfo(info), true);
         provider.syncEmc(player); //Not 100% sure whether this only changes EMC count, so kept it. Prob don't need
     }
     return stack;
} 
```

**Comment by DonovanDMC** [comment]
This is already a thing
> getFilterStatus()

Their nbt filter is on by default

[Read the wiki page](https://github.com/DonovanDMC/ProjectExpansion/wiki/EMC-Link#nbt-filtering)
