### ISSUE TITLE
Issue with refined storage and transmutation interface

### ISSUE THREAD

**Issue by XtraSonicTest** [DonovanDMC/ProjectExpansion#91]
I'm not 100% sure if i should open this issue here or somewhere else, but since it's an issue that i observed because of the transmutation interface, i'll start here.
If your refined storage is hooked up to a transmutation interface and you have more than max int 2147483647 EMC, items costing 1 EMC will be displayed at the max int value instead of the actual amount of  EMC that you have. The real problem with this is that because the system thinks it's full, it will no longer import any of the items which are at the max int value even if they could be imported either into the interface or other places. 
I observed this while playing the mechanical mastery modpack version 1.2.1. Let me know if you need any other details.

**Comment by DonovanDMC** [comment]
Items can't even be inserted into the slot, so its count shouldn't matter
go complain to the authors of the other mod, not us

**Comment by XtraSonicTest** [comment]
Thank you for the fast response and sorry if i irritated you. I was just trying to report a bug, not trying to complain about it. I will open an issue on the refined storage github then. Have a nice day!
