### ISSUE TITLE
[BUG]: Can't craft the Final Star Shard.

### ISSUE THREAD

**Issue by Furious1964** [DonovanDMC/ProjectExpansion#92]
**Description**
I put 1 Nether Star and 8 Colossal Star Omegas in a crafting table and nothing happens. Table says I'm missing the Omegas.

**Minecraft Version**
1.18.2

**ProjectExpansion Version**
1.0.20

**Forge Version**
40.2.1

**Reproduction Steps**
1. Put items in Crafting Table.
2. Table says I don't have any Omegas.

Has the creation of the Final Star Shards been implemented into the Mod?

**Comment by Furious1964** [comment]
Figured out what it was. Can you please make the recipe also use the items from ExtendedeXchange Mod as that's what is used in the Stoneblock 3 Mod Pack. Thanks in advance.

**Comment by DonovanDMC** [comment]
No.
