### ISSUE TITLE
java.lang.NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by Slymix98** [DonovanDMC/ProjectExpansion#93]
[crash-2023-04-27_00.14.03-server.txt](https://github.com/DonovanDMC/ProjectExpansion/files/11358769/crash-2023-04-27_00.14.03-server.txt)

**Comment by DonovanDMC** [comment]
You have way too many mods to be considering that our problem, and there is absolutely nothing in that crash report for me to go off of to even try to find out what's happening

**Comment by mongomay69** [comment]
Project Expanion doesnt play well with mine colonies. playing ATM8 and once i uninstalled it i was good

**Comment by DonovanDMC** [comment]
There's no info in this crash report regardless, so I'm not spending the time on it

**Comment by mongomay69** [comment]
i only say that because mine colonies is in the crash log
