### ISSUE TITLE
"Non [a-z0-9/._-] character in path of location: projectexpansion:pınk_matter" on starting a server. This error is just me, modpack makers have no such problem

### ISSUE THREAD

**Issue by ScarFia** [DonovanDMC/ProjectExpansion#94]
[crash-2023-05-09_15.48.09-fml.txt](https://github.com/DonovanDMC/ProjectExpansion/files/11431316/crash-2023-05-09_15.48.09-fml.txt)

**Comment by DonovanDMC** [comment]
That's a perfectly valid path, look into the other mods you're using.
