### ISSUE TITLE
Game Crashes on Save when added to ATM8 Modpack Due to Forge Version Incompatibility

### ISSUE THREAD

**Issue by wcarroll4** [DonovanDMC/ProjectExpansion#97]
Hello,

I added this mod and all prerequisites to the ATM8 modpack, and was experiencing a consistent crash on save load. According to the team for ATM8, in response to another user with the same problem, this is a problem with this mod because it is "incompatible with Forge version 43.2.8, and you cannot change the forge version [for ATM8] as other mods need that forge version, or they'll crash".

**Comment by DonovanDMC** [comment]
I still have yet to be told ***why*** there's supposedly a problem
I have ran it with forge 43.2.8, and higher, it worked just fine
the only crash reports I've gotten have had no information in them
I'm not going to spend several hours of my time testing combinations of mods to figure out exactly which mod is causing problems

**Comment by ShawnRHayes** [comment]
server tick loop error  is what is showing up on my crash report if that helps

**Comment by DonovanDMC** [comment]
It doesn't
I have no idea what the error is, or what mod it's conflicting with

**Comment by mongomay69** [comment]
from what i saw before it doesn't like mine colonies. I responded on one of your earlier issues you closed

**Comment by mongomay69** [comment]
but i just launched the newest version of ATM8 and its working fine
